Allow hyphens in service annotations
datawire/ambassador-chart pull request #117
Opened 2020-08-12 10:57 UTC by zabudskyi

Hi,
This PR handles cases when there are hyphens in service annotations.

2020-09-11 20:23 UTC, inercia requested changes
Just one thing: could you add an entry in the CHANGELOG (https://github.com/datawire/ambassador-chart/blob/master/CHANGELOG.md) about this change? Right under the `Next Release`.

2020-09-14 09:00 UTC, PavloZabudskyi commented
@inercia 
I added entry in the CHANGELOG, please have a look.

2020-09-14 10:35 UTC, inercia approved these changes

2020-09-14 10:36 UTC, merged

2020-09-14 10:36 UTC, inercia commented
Merged. It will be available in the next release of the Chart. Thanks @PavloZabudskyi .